jenkins_version: 1.608
jenkins_jar_location: /var/lib/jenkins/war/WEB-INF/jenkins-cli.jar
jenkins_hostname: 127.0.0.1
jenkins_http_port: 8000
jenkins_https_port: 8443
jenkins_context: ci
jenkins_base_url: http://{{ jenkins_hostname }}:{{ jenkins_http_port }}/{{ jenkins_context }}
jenkins_spool_dir: /var/spool/jenkins
jenkins_plugins:
  - ant
  - antisamy-markup-formatter
  - build-environment
  - build-failure-analyzer
  - build-monitor-plugin
  - build-name-setter
  - build-timeout
  - build-user-vars-plugin
  - buildtriggerbadge
  - configurationslicing
  - credentials
  - cvs
  - dashboard-view
  - email-ext
  - embeddable-build-status
  - external-monitor-job
  - git-client
  - git-parameter
  - git-server
  - git-tag-message
  - git-userContent
  - git
  - html5-notifier-plugin
  - htmlpublisher
  - jacoco
  - javadoc
  - job-dsl
  - junit
  - ldap
  - m2release
  - mailer
  - mapdb-api
  - mask-passwords
  - matrix-auth
  - matrix-project
  - maven-info
  - maven-metadata-plugin
  - maven-plugin
  - pam-auth
  - pollscm
  - project-description-setter
  - release
  - scm-api
  - script-security
  - ssh-credentials
  - ssh-slaves
  - subversion
  - template-project
  - token-macro
  - translation
  - windows-slaves
maven_download_base_url: http://repo1.maven.org/maven2/org/apache/maven/apache-maven
maven_versions:
  - 2.2.1
  - 3.0.5
  - 3.2.5
  - 3.3.1
maven_current_version: 3.3.1
