---
# These tasks copy the files needed by nginx
- name: Ensure nginx default site is copied.
  template: src={{item}} dest=/{{item}} owner=root group=root mode=0644
  with_items:
    - etc/nginx/sites-available/default
  notify: restart nginx.

- name: Ensure nginx default site is enabled.
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default owner=root group=root state=link

- name: Ensure nginx crt is present.
  copy: src=data/nginx/files/etc/nginx/{{ansible_fdqn}}.crt dest=/etc/nginx/{{ansible_fdqn}}.crt owner=root group=root mode=0444
  notify: restart nginx.

- name: Ensure nginx key are present.
  copy: src=data/nginx/files/etc/nginx/{{ansible_fqdn}}.key dest=/etc/nginx/{{ansible_fqdn}}.key owner=root group=root mode=0400
  notify: restart nginx.
