---
# These tasks copy the files needed by nginx
- name: Ensure nginx default site is copied.
  template: >
    src={{item}}
    dest=/{{item}}
    owner=root
    group=root
    mode=0644
  with_items:
    - etc/nginx/sites-available/default
  notify: restart nginx.

- name: Ensure nginx default site is enabled.
  file: >
    src=/etc/nginx/sites-available/default
    dest=/etc/nginx/sites-enabled/default
    owner=root
    group=root
    state=link

- name: Ensure nginx crt and key are present and have the right permissions.
  copy: >
    src=data/nginx/files/etc/nginx/{{ansible_fqdn}}.{{item.extension}}
    dest=/etc/nginx/{{ansible_fqdn}}.{{item.extension}}
    owner=root
    group=root
    mode={{item.mode}}
  with_items:
  - {extension: crt, mode: 0444} # be less strict this is public.
  - {extension: key, mode: 0400} # be strict here, this is a secret.
  notify: restart nginx.
