---
- name: Install jenkins, nginx and squid3.
  hosts:
  - jenkins
  - vagrant
  pre_tasks:
  - local_action: debug var=gitinfo_revision
  - local_action: debug var=gitinfo_modified
  - name: Ensure GPG keys of Java repository is present.
    apt_key: keyserver="hkp://keyserver.ubuntu.com:80" id="EEA14886"
  - name: Accept the Oracle JDK licenses.
    debconf: name={{item}} question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    with_items:
    - oracle-java7-installer
    - oracle-java8-installer
  - name: Ensure GPG keys of Jenkins repository is present.
    apt_key: url="http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key"
  - apt: update_cache=true cache_valid_time=600
  roles:
  - common
  - jenkins
  - nginx
  - squid3
