---
- name: Install jenkins, nginx and squid3.
  hosts: all
  pre_tasks:
    - apt:
        update_cache: true
        cache_valid_time: 600
  roles:
    - common
    - sudoers
    - java
    - jenkins
    - nginx
    - squid3
    - postfix
  post_tasks:
    - name: Create facts directory
      file:
        path: /etc/ansible/facts.d
        state: directory
    - name: Create provision fact
      copy:
        dest: /etc/ansible/facts.d/provison.fact
        content: |
          [gitinfo]
          revision={{gitinfo.revision}}
          branch={{gitinfo.branch}}
          status={{gitinfo.status}}
          user={{gitinfo.user}}
      changed_when: false
    - name: Update motd
      lineinfile:
        dest: /etc/motd
        regexp: '^MANAGED BY ANSIBLE .*$'
        line: 'MANAGED BY ANSIBLE rev={{gitinfo.revision}}, branch={{gitinfo.branch}}, status={{gitinfo.status}}, user={{gitinfo.user}}'
      changed_when: false
