---
- name: Install jenkins, nginx and squid3.
  hosts:
  - jenkins
  - vagrant
  pre_tasks:
  - local_action: debug var=gitinfo_revision
  - local_action: debug var=gitinfo_modified
  - local_action: debug var=gitinfo_branch
  roles:
  - common
  - java
  - jenkins
  - nginx
  - squid3
