---
- name: Install jenkins, nginx and squid3.
  hosts:
  - all
  pre_tasks:
  - apt: update_cache=true
  roles:
  - common
  - sudoers
  - java
  - jenkins
  - nginx
  - squid3
  - postfix
  post_tasks:
  - lineinfile:
      dest=/etc/motd
      regexp='^MANAGED BY ANSIBLE .*$'
      line='MANAGED BY ANSIBLE rev={{gitinfo_revision}}, branch={{gitinfo_branch}} status={{gitinfo_modified}}'
