---
- name: Install jenkins, nginx and squid3.
  hosts:
  - jenkins
  - vagrant
  pre_tasks:
  - local_action: debug var=gitinfo_revision
  - local_action: debug var=gitinfo_modified
  - local_action: debug var=gitinfo_branch
  roles:
  - common
  - java
  - jenkins
  - nginx
  - squid3
  post_tasks:
  - lineinfile: dest=/etc/motd regexp="^MANAGED BY ANSIBLE .*$" line="MANAGED BY ANSIBLE rev={{gitinfo_revision}}, branch={{gitinfo_branch}} status={{gitinfo_modified}}"
