---
# These tasks add the needed repositories for Jenkins
- name: Ensure GPG keys of Jenkins repository is present.
  apt_key:
    data: "{{ jenkins_ci_org_key }}"
    state: present
- name: Ensure needed Jenkins repository lists is added.
  apt_repository:
    repo: "deb http://pkg.jenkins-ci.org/debian binary/"
    state: present
    update_cache: True
