---
# These tasks copy the files needed by jenkins
- name: Ensure jenkins default is copied.
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - etc/default/jenkins
  notify: restart jenkins

- name: Ensure jenkins .m2 and .vnc directories do exist.
  file:
    path: /var/lib/jenkins/{{ item.name }}/
    state: directory
    owner: jenkins
    group: jenkins
    mode: "{{ item.mode }}"
  with_items:
    - { name: ".m2", mode: "0750" }
    - { name: ".vnc", mode: "0700" }

- name: Ensure jenkins maven files exist.
  copy:
    src: "m2/{{item}}"
    dest: "/var/lib/jenkins/.m2/{{item}}"
    owner: jenkins
    group: jenkins
    mode: 0640
  with_items:
    - settings.xml
    - toolchains.xml

- name: Ensure seperate jenkins home directory does exist for builds and workspaces
  file:
    path: /home/jenkins/{{ item }}
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0750
  with_items:
    - builds
    - workspace
    - m2repo
