- name: Create Jenkins updates folder.
  file:
    path: /var/lib/jenkins/updates
    owner: jenkins
    group: jenkins
    mode: 0755
    state: directory

- name: Update plugin data.
  command: curl -s '{{ jenkins_base_url }}/updateCenter/site/default/api/json?pretty=true&tree=updates'
  changed_when: false

- name: Get list of outdated plugins
  shell: "{{ jenkins_cli_command }} list-plugins | awk '$0~/\\)$/{ print $1 }'"
  register: outdated_plugins
  changed_when: outdated_plugins.stdout_lines

- name: Install additional Jenkins plugins.
  command: "{{ jenkins_cli_command }} install-plugin {{ item }}"
  args:
    creates: /var/lib/jenkins/plugins/{{ item }}.jpi
  with_items: jenkins_plugins
  notify: restart jenkins

- name: Update outdated Jenkins plugins.
  command: "{{ jenkins_cli_command }} install-plugin {{ item }}"
  with_items: outdated_plugins.stdout_lines
  notify: restart jenkins