- name: Create Maven base directory
  file:
    path: /usr/local/maven
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Fetch and unpack Maven distributions.
  shell: curl --silent {{ maven_download_base_url }}/{{ item }}/apache-maven-{{ item }}-bin.tar.gz | tar xz
  args:
    chdir: /usr/local/maven
    creates: /usr/local/maven/apache-maven-{{ item }}/bin/mvn
  with_items: maven_versions

- name: Create symlinks for default Maven.
  file:
    dest: /usr/local/bin/{{ item }}
    src: /usr/local/maven/apache-maven-{{ maven_current_version }}/bin/{{ item }}
    state: link
  with_items:
    - mvn
    - mvnDebug

- name: Create Maven configuration for Jenkins.
  template:
    src: var/lib/jenkins/hudson.tasks.Maven.xml
    dest: /var/lib/jenkins/hudson.tasks.Maven.xml
  notify: restart jenkins
    