---
- name: Install needed base packages for development.
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - autotools-dev
    - bpython
    - build-essential
    - coreutils
    - devscripts
    - git
    - htop
    - libxml2
    - libxml2-dev
    - libxml2-utils
    - makedev
    - manpages-dev
    - markdown
    - ntp
    - python-dev
    - python-pip
    - python-virtualenv
    - python2.7-dev
    - ruby-dev
    - screen
    - subversion
    - tmux
    - xml-core
- name: Ensure rpcbind is stopped.
  service:
    name: "{{item}}"
    state: stopped
    enabled: no
  with_items:
    - rpcbind
    - nfs-common

- name: Create jsonpp
  copy:
    dest: /usr/local/bin/jsonpp
    mode: 0755
    content: |
        #!/usr/bin/python
        import json, pprint,sys
        pprint.pprint(json.load(sys.stdin))